'use strict';function y(e,a,b,c,g){e.v.sc(e.ab,a,b,c,g)}function B(e,a,b,c){e.v.ea?y(e,a,b,c):e.v.nf()._OnMessageFromDOM({type:"event",component:e.ab,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function G(e,a,b){e.v.C(e.ab,a,b)}function I(e,a){for(const [b,c]of a)G(e,b,c)}function J(e){e.Sb||(e.v.Ye(e.he),e.Sb=!0)}function K(e){e.Sb&&(e.v.jg(e.he),e.Sb=!1)}window.yb=class{constructor(e,a){this.v=e;this.ab=a;this.Sb=!1;this.he=()=>this.wa()}hd(){}wa(){}};
function M(e){-1!==e.Pa&&(self.clearTimeout(e.Pa),e.Pa=-1)}window.Pe=class{constructor(e,a){this.Nc=e;this.Kg=a;this.Pa=-1;this.Ub=-Infinity;this.ie=()=>{this.Pa=-1;this.Ub=Date.now();this.gb=!0;this.Nc();this.gb=!1};this.Rd=this.gb=!1}c(){M(this);this.ie=this.Nc=null}};"use strict";
function O(e,a){const b=a.elementId,c=e.md(b,a);e.V.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{P(e,"elem-focused",b)});c.addEventListener("blur",()=>{P(e,"elem-blurred",b)});e.$a&&document.body.appendChild(c)}function Q(e,a,b){G(e,a,c=>{const g=e.V.get(c.elementId);return b(g,c)})}function P(e,a,b,c){c||(c={});c.elementId=b;y(e,a,c)}
window.Be=class extends self.yb{constructor(e,a){super(e,a);this.V=new Map;this.$a=!0;I(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const c=this.V.get(b);this.od(c);this.$a&&c.parentElement.removeChild(c);this.V.delete(b)}}],["set-visible",b=>{this.$a&&(this.V.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.$a){var c=this.V.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";
b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{this.V.get(b.elementId);this.xd()}],["focus",b=>{{const c=this.V.get(b.elementId);b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.V.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.V.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.V.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}md(){throw Error("required override");}od(){}xd(){throw Error("required override");
}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const d=document.createElement("script");d.async=!1;d.type="module";return h.Wg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=h.$g+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=h;document.head.appendChild(d)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(h){}c=!0}return g}let p=
new Audio;const u={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(h){h=await C(h);return(new TextDecoder("utf-8")).decode(h)}function C(h){return new Promise((d,
k)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(h)})}const v=[];let w=0;window.RealFile=window.File;const D=[],H=new Map,z=new Map;let L=0;const E=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");E.push(h)};const N=new Set(["cordova","playable-ad","instant-games"]);let f=!1;window.Va=class h{constructor(d){this.ea=d.bh;this.ra=null;this.F="";this.ec=d.Zg;this.vb={};this.Ia=this.ub=null;
this.Qb=[];this.jb=this.K=this.Na=null;this.Ma=-1;this.Pg=()=>this.Pf();this.La=[];this.A=d.je;this.hb="file"===location.protocol.substr(0,4);!this.ea||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ea=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ea=!1;if("cordova"===this.A&&this.ea)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this.ea=!1)}else this.ea=!1;this.Wb=this.ja=null;"html5"!==
this.A&&"playable-ad"!==this.A||!this.hb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.wf(k));this.C("runtime","create-job-worker",()=>this.xf());"cordova"===this.A?document.addEventListener("deviceready",()=>this.Cd(d)):this.Cd(d)}c(){this.yc();this.ra&&(this.ra=this.ra.onmessage=null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ia&&
(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Ke(){return e&&"cordova"===this.A}rc(){const d=navigator.userAgent;return e&&N.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}async Cd(d){"macos-wkwebview"===this.A&&this.mg();if("playable-ad"===this.A){this.ja=self.c3_base64files;this.Wb={};await this.cf();for(let l=0,n=d.Qa.length;l<n;++l){var k=d.Qa[l].toLowerCase();this.Wb.hasOwnProperty(k)?d.Qa[l]={Wg:!0,$g:this.Wb[k]}:this.ja.hasOwnProperty(k)&&
(d.Qa[l]=URL.createObjectURL(this.ja[k]))}}d.Rg?this.F=d.Rg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));d.eh&&(this.vb=d.eh);k=new MessageChannel;this.ra=k.port1;this.ra.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Jf(l));this.jb=new self.Le(this);await R(this.jb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===
typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ea?await this.qf(d,k.port2):await this.pf(d,k.port2)}Bc(d){d=this.vb.hasOwnProperty(d)?this.vb[d]:d.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?this.vb["workermain.js"]:"playable-ad"===this.A&&this.ja.hasOwnProperty(d.toLowerCase())?this.ja[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async lc(d,k,l){if(d.startsWith("blob:"))return new Worker(d,l);if("cordova"===this.A&&
this.hb)return d=await this.xb(l.Vg?d:this.ec+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,l)}ya(){return Math.max(window.innerWidth,1)}xa(){return Math.max(window.innerHeight,1)}Bd(d){var k=this.jb;return{baseUrl:this.F,windowInnerWidth:this.ya(),windowInnerHeight:this.xa(),
devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ta(),projectData:d.jh,previewImageBlobs:window.cr_previewImageBlobs||this.ja,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.hh||"",exportType:d.je,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ih,jobScheduler:{inputPort:k.Uc,outputPort:k.ad,maxNumWorkers:k.Mg},supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ec+"opus.wasm.js",
opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ec+"opus.wasm.wasm",isFileProtocol:this.hb,isiOSCordova:this.Ke(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async qf(d,k){var l=this.Bc(d.dh);this.ub=await this.lc(l,this.F,{type:"module",name:"Runtime",Vg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let n=d.gd||[],t=d.Qa;n=await Promise.all(n.map(q=>
this.Ea(q)));t=await Promise.all(t.map(q=>this.Ea(q)));if("cordova"===this.A)for(let q=0,r=d.jc.length;q<r;++q){const x=d.jc[q],F=x[0];if(F===d.ed||"scriptsInEvents.js"===F||F.endsWith("/scriptsInEvents.js"))x[1]=await this.Ea(F)}this.ub.postMessage(Object.assign(this.Bd(d),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:t,projectScripts:d.jc,mainProjectScript:d.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...S(this.jb)]);this.Qb=D.map(q=>
new q(this));this.Ad();self.c3_callFunction=(q,r)=>this.Na.rf(q,r);"preview"===this.A&&(self.goToLastErrorScript=()=>this.sc("runtime","go-to-last-error-script"))}async pf(d,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Qb=D.map(q=>new q(this));this.Ad();var l=d.Qa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(d.gd)&&l.unshift(...d.gd);l=await Promise.all(l.map(q=>this.Ea(q)));await Promise.all(l.map(q=>
b(q)));l=self.C3_ProjectScriptsStatus;const n=d.ed,t=d.jc;for(let [q,r]of t)if(r||(r=q),q===n)try{r=await this.Ea(r),await b(r),"preview"!==this.A||l[q]||this.Ld(q,"main script did not run to completion")}catch(x){this.Ld(q,x)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))r=await this.Ea(r),await b(r);"preview"===this.A&&"object"!==typeof self.fh.gh?(this.Kb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.Bd(d),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:E}),this.Ed(),this.Ia=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Ia,d))}Ld(d,k){this.Kb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ed(){this.Kb()}Kb(){const d=
window.Sg;d&&(d.parentElement.removeChild(d),window.Sg=null)}async xf(){const d=await T(this.jb);return{outputPort:d,transferables:[d]}}nf(){if(this.ea)throw Error("not available in worker mode");return this.Ia}sc(d,k,l,n,t){this.ra.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:null},t)}sd(d,k,l,n,t){const q=L++,r=new Promise((x,F)=>{z.set(q,{resolve:x,reject:F})});this.ra.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:q},
t);return r}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this.Cf(d);if("result"===k)this.Sf(d);else if("runtime-ready"===k)this.Tf();else if("alert-error"===k)this.Kb(),alert(d.message);else if("creating-runtime"===k)this.Ed();else throw Error(`unknown message '${k}'`);}Cf(d){const k=d.component,l=d.handler,n=d.data,t=d.responseId;if(d=H.get(k))if(d=d.get(l)){var q=null;try{q=d(n)}catch(r){console.error(`Exception in '${k}' handler '${l}':`,r);null!==t&&this.Jb(t,!1,""+r);return}if(null===
t)return q;q&&q.then?q.then(r=>this.Jb(t,!0,r)).catch(r=>{console.error(`Rejection from '${k}' handler '${l}':`,r);this.Jb(t,!1,""+r)}):this.Jb(t,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Jb(d,k,l){let n;l&&l.transferables&&(n=l.transferables);this.ra.postMessage({type:"result",responseId:d,isOk:k,result:l},n)}Sf(d){const k=d.responseId,l=d.isOk;d=d.result;const n=z.get(k);l?n.resolve(d):n.reject(d);z.delete(k)}C(d,
k,l){let n=H.get(d);n||(n=new Map,H.set(d,n));if(n.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);n.set(k,l)}static wb(d){if(D.includes(d))throw Error("DOM handler already added");D.push(d)}Ad(){for(const d of this.Qb)if("runtime"===d.ab){this.Na=d;return}throw Error("cannot find runtime DOM handler");}Jf(d){this.sc("debugger","message",d)}Tf(){for(const d of this.Qb)d.hd()}static Ta(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
f)}static Md(d){f=!!d}Ye(d){this.La.push(d);this.Lc()}jg(d){d=this.La.indexOf(d);if(-1===d)throw Error("invalid callback");this.La.splice(d,1);this.La.length||this.yc()}Lc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Pg))}yc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Pf(){this.Ma=-1;for(const d of this.La)d();this.Lc()}Z(d){this.Na.Z(d)}aa(d){this.Na.aa(d)}Kc(){this.Na.Kc()}Eb(d){this.Na.Eb(d)}Je(){return!!u["audio/webm; codecs=opus"]}async Ig(d){d=await this.sd("runtime",
"opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}Ie(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}rd(d){return!this.Ie(d)}async Ea(d){return"cordova"===this.A&&(d.startsWith("file:")||this.hb&&this.rd(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),d=await this.xb(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async wf(d){const k=d.filename;switch(d.as){case "text":return await this.Ae(k);case "buffer":return await this.xb(k);
default:throw Error("unsupported type");}}ld(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,t=>{t.file(l,n)},n)})}async Ae(d){d=await this.ld(d);return await A(d)}zc(){if(v.length&&!(8<=w)){w++;var d=v.shift();this.df(d.filename,d.ah,d.Ug)}}xb(d){return new Promise((k,l)=>{v.push({filename:d,ah:n=>{w--;this.zc();k(n)},Ug:n=>{w--;this.zc();l(n)}});this.zc()})}async df(d,k,l){try{const n=await this.ld(d),t=await C(n);
k(t)}catch(n){l(n)}}mg(){var d={type:"ready"};if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async cf(){const d=[];for(const [k,l]of Object.entries(this.ja))d.push(this.bf(k,l));await Promise.all(d)}async bf(d,k){if("object"===typeof k)this.ja[d]=new Blob([k.str],{type:k.type}),this.Wb[d]=k.str;else{let l=await this.lf(k);
l||(l=this.ff(k));this.ja[d]=l}}async lf(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}ff(d){d=this.dg(d);return this.af(d.data,d.Xg)}dg(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);k=d.substring(5,k).split(";");d=k[0]||
"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Xg:d,data:l}}af(d,k){var l=d.length;let n=l>>2,t=new Uint8Array(l),q=new Uint32Array(t.buffer,0,n),r,x;for(x=r=0;r<n;++r)q[r]=d.charCodeAt(x++)|d.charCodeAt(x++)<<8|d.charCodeAt(x++)<<16|d.charCodeAt(x++)<<24;for(l&=3;l--;)t[x]=d.charCodeAt(x),++x;return new Blob([t],{type:k})}}}"use strict";
{const e=self.Va;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((h,d)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>d(l);k.rel=
"stylesheet";k.href=f;document.head.appendChild(k)})}function u(f){return new Promise((h,d)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>d(l);k.src=f})}async function A(f){f=URL.createObjectURL(f);try{return await u(f)}finally{URL.revokeObjectURL(f)}}function C(f){return new Promise((h,d)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>d(l);k.readAsText(f)})}async function v(f,h,d){if(!/firefox/i.test(navigator.userAgent))return await A(f);var k=await C(f);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),t=l.getAttribute("height");if(!n.includes("%")&&!t.includes("%"))return await A(f)}l.setAttribute("width",h+"px");l.setAttribute("height",d+"px");k=(new XMLSerializer).serializeToString(k);f=new Blob([k],{type:"image/svg+xml"});return await A(f)}function w(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const D=new Set(["input",
"textarea","datalist","select"]),H=new Set(["canvas","body","html"]);function z(f){H.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function L(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await A(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const h=f.getBoundingClientRect();document.body.removeChild(f);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(f,h,d,k,l){f=await v(f,h,d);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(f,0,0,h,d);return n};let E=!1;document.addEventListener("pause",()=>E=!0);document.addEventListener("resume",()=>E=!1);function N(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}e.wb(class extends self.yb{constructor(f){super(f,"runtime");this.Wd=!0;this.Oa=-1;this.cd="any";this.Nd=this.Od=!1;this.Xc=
this.rb=this.Aa=null;f.C("canvas","update-size",k=>this.ag(k));f.C("runtime","invoke-download",k=>this.Hf(k));f.C("runtime","raster-svg-image",k=>this.Qf(k));f.C("runtime","get-svg-image-size",k=>this.Ef(k));f.C("runtime","set-target-orientation",k=>this.Yf(k));f.C("runtime","register-sw",()=>this.Rf());f.C("runtime","post-to-debugger",k=>this.Gd(k));f.C("runtime","go-to-script",k=>this.Gd(k));f.C("runtime","before-start-ticking",()=>this.vf());f.C("runtime","debug-highlight",k=>this.yf(k));f.C("runtime",
"enable-device-orientation",()=>this.$e());f.C("runtime","enable-device-motion",()=>this.Ze());f.C("runtime","add-stylesheet",k=>this.tf(k));f.C("runtime","alert",k=>this.uf(k));f.C("runtime","hide-cordova-splash",()=>this.Ff());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const d=f.K;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",z);d.addEventListener("selectstart",
z);d.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),d.addEventListener("pointerdown",z)):d.addEventListener("touchstart",z);this.ob=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",L,{passive:!1});window.addEventListener("wheel",L,{passive:!1});window.addEventListener("resize",()=>this.bg());window.addEventListener("fullscreenchange",
()=>this.Wa());window.addEventListener("webkitfullscreenchange",()=>this.Wa());window.addEventListener("mozfullscreenchange",()=>this.Wa());window.addEventListener("fullscreenerror",k=>this.Gc(k));window.addEventListener("webkitfullscreenerror",k=>this.Gc(k));window.addEventListener("mozfullscreenerror",k=>this.Gc(k));f.rc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):w(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.cg(k);this.Ja=new Set;this.Xb=new WeakSet;this.qa=!1}vf(){"cordova"===this.v.A?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!E)}}hd(){window.addEventListener("focus",()=>
this.Ya("window-focus"));window.addEventListener("blur",()=>{this.Ya("window-blur",{parentHasFocus:N()});this.ob=0});window.addEventListener("focusin",h=>{h=h.target;(D.has(h.tagName.toLowerCase())||w(h))&&this.Ya("keyboard-blur")});window.addEventListener("keydown",h=>this.Fd("keydown",h));window.addEventListener("keyup",h=>this.Fd("keyup",h));window.addEventListener("dblclick",h=>this.Hc("dblclick",h,c));window.addEventListener("wheel",h=>this.Lf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Cc(h);this.Xa("pointerdown",h)}),this.v.ea&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.Pe(()=>this.jf(),5),this.rb.Rd=!0,window.addEventListener("pointerrawupdate",h=>this.Of(h))):window.addEventListener("pointermove",h=>this.Xa("pointermove",h)),window.addEventListener("pointerup",h=>this.Xa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Xa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Cc(h);this.Ic("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Ic("pointermove",h)),window.addEventListener("mouseup",h=>this.Ic("pointerup",h)),window.addEventListener("touchstart",h=>{this.Cc(h);this.Ib("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Ib("pointermove",h)),window.addEventListener("touchend",h=>this.Ib("pointerup",h)),window.addEventListener("touchcancel",h=>this.Ib("pointercancel",h)));const f=()=>this.Kc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",
f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}Ya(f,h){y(this,f,h||null,m)}ya(){return this.v.ya()}xa(){return this.v.xa()}bg(){const f=this.ya(),h=this.xa();this.Ya("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Ta()});this.v.rc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Hd(f,h,0))}kg(f,h,d){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Hd(f,
h,d),48)}Hd(f,h,d){const k=this.ya(),l=this.xa();this.Oa=-1;k!=f||l!=h?this.Ya("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.Ta()}):10>d&&this.kg(k,l,d+1)}Yf(f){this.cd=f.targetOrientation}Eg(){const f=this.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(f):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(f):screen.mozLockOrientation?h=screen.mozLockOrientation(f):screen.msLockOrientation&&(h=screen.msLockOrientation(f));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Wa(){const f=e.Ta();f&&"any"!==this.cd&&this.Eg();y(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.ya(),innerHeight:this.xa()})}Gc(f){console.warn("[Construct 3] Fullscreen request failed: ",f);y(this,"fullscreenerror",
{isFullscreen:e.Ta(),innerWidth:this.ya(),innerHeight:this.xa()})}Jc(f){f?this.v.yc():this.v.Lc();y(this,"visibilitychange",{hidden:f})}Fd(f,h){"Backspace"===h.key&&z(h);const d=b.get(h.code)||h.code;B(this,f,{code:d,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}Lf(f){y(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,
timeStamp:f.timeStamp},c)}Hc(f,h,d){a(h)||B(this,f,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},d)}Ic(f,h){if(!a(h)){var d=this.ob;"pointerdown"===f&&0!==d?f="pointermove":"pointerup"===f&&0!==h.buttons&&(f="pointermove");B(this,f,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.ob=h.buttons;this.Hc(h.type,h,g)}}Xa(f,h){if(this.rb&&"pointermove"!==f){var d=this.rb;d.gb||(M(d),d.Ub=Date.now())}d=0;"mouse"===h.pointerType&&(d=this.ob);B(this,f,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:d,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);"mouse"===h.pointerType&&(d="mousemove","pointerdown"===f?d="mousedown":"pointerup"===f&&(d="mouseup"),this.Hc(d,h,g),this.ob=h.buttons)}Of(f){this.Xc=f;f=this.rb;if(-1===f.Pa){var h=Date.now(),d=h-f.Ub,k=f.Kg;d>=k&&f.Rd?(f.Ub=h,f.gb=!0,f.Nc(),f.gb=!1):f.Pa=self.setTimeout(f.ie,Math.max(k-d,4))}}jf(){this.Xa("pointermove",this.Xc);this.Xc=null}Ib(f,h){for(let d=0,k=h.changedTouches.length;d<k;++d){const l=h.changedTouches[d];B(this,f,{pointerId:l.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},c)}}Cc(f){window!==window.top&&window.focus();this.Dd(f.target)&&document.activeElement&&!this.Dd(document.activeElement)&&document.activeElement.blur()}Dd(f){return!f||f===document||
f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}$e(){this.Od||(this.Od=!0,window.addEventListener("deviceorientation",f=>this.Af(f)),window.addEventListener("deviceorientationabsolute",f=>this.Bf(f)))}Ze(){this.Nd||(this.Nd=!0,window.addEventListener("devicemotion",f=>this.zf(f)))}Af(f){y(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},
c)}Bf(f){y(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},c)}zf(f){let h=null;var d=f.acceleration;d&&(h={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var k=f.accelerationIncludingGravity;k&&(d={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=f.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});y(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:d,rotationRate:k,interval:f.interval,timeStamp:f.timeStamp},
c)}ag(f){const h=this.v.K;h.style.width=f.styleWidth+"px";h.style.height=f.styleHeight+"px";h.style.marginLeft=f.marginLeft+"px";h.style.marginTop=f.marginTop+"px";this.Wd&&(h.style.display="",this.Wd=!1)}Hf(f){const h=f.url;f=f.filename;const d=document.createElement("a"),k=document.body;d.textContent=f;d.href=h;d.download=f;k.appendChild(d);d.click();k.removeChild(d)}async Qf(f){var h=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);
h=h?await createImageBitmap(f,h):await createImageBitmap(f);return{imageBitmap:h,transferables:[h]}}async Ef(f){return await self.C3_GetSvgImageSize(f.blob)}async tf(f){await p(f.url)}Kc(){var f=[...this.Ja];this.Ja.clear();if(!this.qa)for(const h of f)(f=h.play())&&f.catch(()=>{this.Xb.has(h)||this.Ja.add(h)})}Z(f){if("function"!==typeof f.play)throw Error("missing play function");this.Xb.delete(f);let h;try{h=f.play()}catch(d){this.Ja.add(f);return}h&&h.catch(()=>{this.Xb.has(f)||this.Ja.add(f)})}aa(f){this.Ja.delete(f);
this.Xb.add(f)}Eb(f){this.qa=!!f}Ff(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}yf(f){if(f.show){this.Aa||(this.Aa=document.createElement("div"),this.Aa.id="inspectOutline",document.body.appendChild(this.Aa));var h=this.Aa;h.style.display="";h.style.left=f.left-1+"px";h.style.top=f.top-1+"px";h.style.width=f.width+2+"px";h.style.height=f.height+2+"px";h.textContent=f.name}else this.Aa&&(this.Aa.style.display="none")}Rf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Gd(f){window.c3_postToMessagePort&&
(f.from="runtime",window.c3_postToMessagePort(f))}rf(f,h){return this.v.sd(this.ab,"js-invoke-function",{name:f,params:h},void 0,void 0)}uf(f){alert(f.message)}cg(f){"entered-fullscreen"===f?(e.Md(!0),this.Wa()):"exited-fullscreen"===f?(e.Md(!1),this.Wa()):console.warn("Unknown wrapper message: ",f)}})}"use strict";
async function R(e){if(e.Jg)throw Error("already initialised");e.Jg=!0;var a=e.dc.Bc("dispatchworker.js");e.Qc=await e.dc.lc(a,e.F,{name:"DispatchWorker"});a=new MessageChannel;e.Uc=a.port1;e.Qc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.ad=await T(e)}function S(e){return[e.Uc,e.ad]}
async function T(e){const a=e.Xd.length;var b=e.dc.Bc("jobworker.js");b=await e.dc.lc(b,e.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;e.Qc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);e.Xd.push(b);return g.port1}
self.Le=class{constructor(e){this.dc=e;this.F=e.F;this.F="preview"===e.A?this.F+"workers/":this.F+e.ec;this.Mg=Math.min(navigator.hardwareConcurrency||2,16);this.Qc=null;this.Xd=[];this.ad=this.Uc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Va({bh:!0,dh:"workermain.js",Qa:["scripts/c3runtime.js"],jc:[],ed:"",Zg:"scripts/",gd:["box2d.wasm.js"],je:"html5"}));"use strict";
{const e=180/Math.PI;self.fa=class extends self.yb{constructor(a){super(a,"audio");this.Pb=this.f=null;this.Rb=this.Tc=!1;this.ta=()=>this.Fg();this.ca=[];this.D=[];this.ia=null;this.Yd="";this.Zd=-1;this.qb=new Map;this.Yc=1;this.qa=!1;this.dd=0;this.hc=1;this.Rc=0;this.ae="HRTF";this.Sd="inverse";this.be=600;this.$d=1E4;this.de=1;this.Ud=this.bd=!1;this.ge=this.v.Je();this.da=new Map;this.Ga=new Set;this.Vc=!1;this.Zc="";this.Ba=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Kf(b,c);this.Ob=null;
self.C3Audio_GetOutputStream=()=>this.Df();self.C3Audio_DOMInterface=this;I(this,[["create-audio-context",b=>this.ef(b)],["play",b=>this.eg(b)],["stop",b=>this.Cg(b)],["stop-all",()=>this.Dg()],["set-paused",b=>this.vg(b)],["set-volume",b=>this.Ag(b)],["fade-volume",b=>this.kf(b)],["set-master-volume",b=>this.tg(b)],["set-muted",b=>this.ug(b)],["set-silent",b=>this.xg(b)],["set-looping",b=>this.sg(b)],["set-playback-rate",b=>this.wg(b)],["seek",b=>this.lg(b)],["preload",b=>this.fg(b)],["unload",b=>
this.Gg(b)],["unload-all",()=>this.Hg()],["set-suspended",b=>this.yg(b)],["add-effect",b=>this.yd(b)],["set-effect-param",b=>this.pg(b)],["remove-effects",b=>this.hg(b)],["tick",b=>this.$f(b)],["load-state",b=>this.If(b)]])}async ef(a){a.isiOSCordova&&(this.bd=!0);this.dd=a.timeScaleMode;this.ae=["equalpower","HRTF","soundfield"][a.panningModel];this.Sd=["linear","inverse","exponential"][a.distanceModel];this.be=a.refDistance;this.$d=a.maxDistance;this.de=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ge||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.zd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.zd()};this.Pb=this.f.createGain();this.Pb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.mc();try{await Promise.all(a.preloadList.map(c=>this.Gb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}zd(){this.Rb||(this.Tc=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Rb=!0)}gf(){this.Rb&&(this.Tc=!0,window.removeEventListener("pointerup",this.ta,!0),window.removeEventListener("touchend",
this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Rb=!1)}Fg(){if(!this.Tc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.gf()}}X(){return this.f}mc(){return this.f.currentTime}ua(){return this.Pb}pd(a){return(a=this.da.get(a.toLowerCase()))?a[0].P():this.ua()}ke(a,b){a=a.toLowerCase();let c=this.da.get(a);
c||(c=[],this.da.set(a,c));b.rg(c.length);b.zg(a);c.push(b);this.Kd(a)}Kd(a){let b=this.ua();const c=this.da.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.ua()):p.S(c[g+1].P())}}for(const g of this.na(a))g.Qe(b);this.Ba&&this.Zc===a&&(this.Ba.disconnect(),this.Ba.connect(b))}Ab(){return this.Yc}Bb(){return this.qa}qg(){this.Ud=!0}De(a,b){return b?this.v.Ig(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}Z(a){this.v.Z(a)}aa(a){this.v.aa(a)}td(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Re(){let a=0;for(let b=0,c=this.ca.length;b<c;++b){const g=this.ca[b];this.ca[a]=g;g.va()?g.c():++a}this.ca.length=a}*na(a){if(a)for(const b of this.D)self.fa.Ee(b.$,a)&&(yield b);else this.ia&&!this.ia.T()&&(yield this.ia)}async Gb(a,b,c,g,m){for(const p of this.ca)if(p.Sa()===b)return await U(p),
p;if(m)return null;g&&(this.bd||this.Ud)&&this.Re();m="audio/webm; codecs=opus"===c&&!this.ge;g&&m&&this.qg();a=!g||this.bd||m?new self.ye(this,a,b,c,g,m):new self.we(this,a,b,c,g);this.ca.push(a);await U(a);return a}async Ac(a,b,c,g,m){for(const p of this.D)if(p.Sa()===b&&(p.kc()||m))return p.Te(g),p;a=await this.Gb(a,b,c,m);g="html5"===a.Mc?new self.xe(a.i,a,g):new self.ze(a.i,a,g);this.D.push(g);return g}Xe(a){let b=this.qb.get(a);if(!b){let c=null;b={fd:0,Yg:new Promise(g=>c=g),resolve:c};this.qb.set(a,
b)}b.fd++}ig(a){const b=this.qb.get(a);if(!b)throw Error("expected pending tag");b.fd--;0===b.fd&&(b.resolve(),this.qb.delete(a))}xc(a){a||(a=this.Yd);return(a=this.qb.get(a))?a.Yg:Promise.resolve()}Hb(){if(0<this.Ga.size)J(this);else for(const a of this.D)if(a.qd()){J(this);break}}wa(){for(var a of this.Ga)a.wa();a=this.mc();for(var b of this.D)b.wa(a);b=this.D.filter(c=>c.qd()).map(c=>c.Ra());y(this,"state",{tickCount:this.Zd,audioInstances:b,analysers:[...this.Ga].map(c=>c.Ge())});0===b.length&&
0===this.Ga.size&&K(this)}tc(a,b,c){y(this,"trigger",{type:a,tag:b,aiid:c})}async eg(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,u=a.isLooping,A=a.vol,C=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Yd=p;this.Xe(p);try{this.ia=await this.Ac(b,c,g,p,m),v?(this.ia.Db(!0),this.ia.Se(v.x,v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),
v.hasOwnProperty("uid")&&this.ia.Ue(v.uid)):this.ia.Db(!1),this.ia.Play(u,A,C,w)}catch(D){console.error("[Construct 3] Audio: error starting playback: ",D);return}finally{this.ig(p)}J(this)}Cg(a){a=a.tag;for(const b of this.na(a))b.oa()}Dg(){for(const a of this.D)a.oa()}vg(a){const b=a.tag;a=a.paused;for(const c of this.na(b))a?c.Ua():c.Cb();this.Hb()}Ag(a){const b=a.tag;a=a.vol;for(const c of this.na(b))c.Fb(a)}async kf(a){const b=a.tag,c=a.vol,g=a.duration;a=a.stopOnEnd;await this.xc(b);for(const m of this.na(b))m.Fe(c,
g,a);this.Hb()}tg(a){this.Yc=a.vol;for(const b of this.D)b.Mb()}ug(a){const b=a.tag;a=a.isMuted;for(const c of this.na(b))c.ud(a)}xg(a){this.qa=a.isSilent;this.v.Eb(this.qa);for(const b of this.D)b.Lb()}sg(a){const b=a.tag;a=a.isLooping;for(const c of this.na(b))c.vc(a)}async wg(a){const b=a.tag;a=a.rate;await this.xc(b);for(const c of this.na(b))c.wd(a)}async lg(a){const b=a.tag;a=a.pos;await this.xc(b);for(const c of this.na(b))c.uc(a)}async fg(a){const b=a.originalUrl,c=a.url,g=a.type;a=a.isMusic;
try{await this.Ac(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async Gg(a){if(a=await this.Gb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ca.indexOf(a),-1!==a&&this.ca.splice(a,1)}Hg(){for(const a of this.ca)a.c();this.ca.length=0}yg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.wc(a);a&&this.f.suspend&&this.f.suspend()}$f(a){this.hc=a.timeScale;this.Rc=a.gameTime;this.Zd=a.tickCount;if(0!==this.dd)for(var b of this.D)b.Fa();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ha===a&&g.vd(c.x,c.y,c.angle)}}async yd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.qe(this,...g);else if("delay"===b)g=new self.oe(this,...g);else if("convolution"===b){b=null;try{b=await this.Gb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}g=new self.ne(this,b.ba,...g);g.ng(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)g=new self.re(this,...g);else if("phaser"===b)g=new self.te(this,...g);else if("gain"===b)g=new self.se(this,...g);else if("tremolo"===b)g=new self.ve(this,...g);else if("ringmod"===b)g=new self.ue(this,...g);else if("distortion"===b)g=new self.pe(this,...g);else if("compressor"===b)g=new self.me(this,...g);else if("analyser"===b)g=new self.le(this,...g);else throw Error("invalid effect type");this.ke(c,g);this.Jd()}pg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,
p=a.time;a=this.da.get(a.tag);!a||0>b||b>=a.length||(a[b].Y(c,g,m,p),this.Jd())}hg(a){a=a.tag.toLowerCase();const b=this.da.get(a);if(b&&b.length){for(const c of b)c.c();this.da.delete(a);this.Kd(a)}}We(a){this.Ga.add(a);this.Hb()}gg(a){this.Ga.delete(a)}Jd(){this.Vc||(this.Vc=!0,Promise.resolve().then(()=>this.hf()))}hf(){const a={};for(const [b,c]of this.da)a[b]=c.map(g=>g.Ra());y(this,"fxstate",{fxstate:a});this.Vc=!1}async If(a){const b=a.saveLoadMode;if(3!==b)for(var c of this.D)c.va()&&1===
b||(c.va()||2!==b)&&c.oa();for(const g of this.da.values())for(const m of g)m.c();this.da.clear();this.hc=a.timeScale;this.Rc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.qa=a.isSilent;this.v.Eb(this.qa);this.Yc=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.yd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.sf(g,b)));this.Hb()}async sf(a,b){if(3!==b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,
p=a.isMusic,u=a.tag,A=a.isLooping,C=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.Ac(c,g,m,u,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Oe(a.pan);b.Play(A,C,v,0);a.isPlaying||b.Ua();b.Ec(a)}}}Kf(a,b){this.Ba&&this.Ba.disconnect();this.Zc=b.toLowerCase();this.Ba=this.f.createMediaStreamSource(a);this.Ba.connect(this.pd(this.Zc))}Df(){this.Ob||(this.Ob=this.f.createMediaStreamDestination(),this.Pb.connect(this.Ob));return this.Ob.stream}static Ee(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ve(a){return a*e}static Ce(a){return Math.pow(10,a/20)}static nd(a){return Math.max(Math.min(self.fa.Ce(a),1),0)}static Ne(a){return Math.log(a)/Math.log(10)*20}static Me(a){return self.fa.Ne(Math.max(Math.min(a,1),0))}static Tg(a,b){return 1-Math.exp(-b*a)}};self.Va.wb(self.fa)}"use strict";function U(e){e.Vb||(e.Vb=e.Dc());return e.Vb}
self.jd=class{constructor(e,a,b,c,g){this.i=e;this.Og=a;this.Ca=b;this.R=c;this.Lg=g;this.Mc="";this.Vb=null}c(){this.Vb=this.i=null}Dc(){}X(){return this.i.X()}oc(){return this.Og}Sa(){return this.Ca}nc(){return this.R}va(){return this.Lg}ga(){}};"use strict";
self.we=class extends self.jd{constructor(e,a,b,c,g){super(e,a,b,c,g);this.Mc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.kb=this.lb=null;this.J.addEventListener("canplaythrough",()=>!0);this.pb=this.X().createGain();this.nb=null;this.J.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.J&&(this.nb=this.X().createMediaElementSource(this.J),this.nb.connect(this.pb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,m);this.kb&&(this.kb(m),this.kb=this.lb=null)})}c(){this.i.td(this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Dc(){return new Promise((e,a)=>{this.lb=e;this.kb=a;this.J.src=this.Ca})}O(){return this.J}ga(){return this.J.duration}};"use strict";
async function V(e){if(e.za)return e.za;var a=e.i.v;if("cordova"===a.A&&a.rd(e.Ca)&&a.hb)e.za=await a.xb(e.Ca);else{a=await fetch(e.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.za=await a.arrayBuffer()}}async function W(e){if(e.ba)return e.ba;e.ba=await e.i.De(e.za,e.Ng);e.za=null}
self.ye=class extends self.jd{constructor(e,a,b,c,g,m){super(e,a,b,c,g);this.Mc="webaudio";this.ba=this.za=null;this.Ng=!!m}c(){this.i.td(this);this.ba=this.za=null;super.c()}async Dc(){try{await V(this),await W(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,e)}}ga(){return this.ba?this.ba.duration:0}};"use strict";
{let e=0;self.kd=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Nb=e++;this.M=this.X().createGain();this.M.connect(this.ua());this.B=null;this.ib=!1;this.la=[0,0,0];this.ka=[0,0,0];this.H=!0;this.W=this.ma=this.G=!1;this.tb=1;this.Ha=!1;this.sa=1;a=this.i.dd;this.Wc=1===a&&!this.va()||2===a;this.eb=this.ha=-1;this.fe=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}X(){return this.i.X()}ua(){return this.i.pd(this.$)}Ab(){return this.i.Ab()}zb(){return this.Wc?
this.i.Rc:performance.now()/1E3}oc(){return this.L.oc()}Sa(){return this.L.Sa()}nc(){return this.L.nc()}va(){return this.L.va()}Te(a){this.$=a}T(){}kc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}qd(){return!this.H&&!this.T()}Da(){}ga(){return this.L.ga()}Play(){}oa(){}Ua(){}Cb(){}Fb(a){this.tb=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.pc()}Fe(a,b,c){if(!this.Ha){a*=this.Ab();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.mc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.tb=a;this.eb=b;this.fe=c}}Mb(){this.Fb(this.tb)}wa(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.fe&&this.oa(),this.i.tc("fade-ended",this.$,this.Nb))}pc(){const a=this.tb*this.Ab();return isFinite(a)?a:0}ud(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Lb())}Bb(){return this.i.Bb()}Lb(){}vc(){}wd(a){this.sa!==a&&(this.sa=a,this.Fa())}Fa(){}uc(){}wc(){}Db(a){a=!!a;this.ib!==a&&((this.ib=a)?(this.B||(this.B=this.X().createPanner(),this.B.panningModel=this.i.ae,this.B.distanceModel=
this.i.Sd,this.B.refDistance=this.i.be,this.B.maxDistance=this.i.$d,this.B.rolloffFactor=this.i.de),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ua())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ua())))}Se(a,b,c,g,m,p){this.ib&&(this.vd(a,b,c),a=self.fa.Ve,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}vd(a,b,c){this.ib&&(this.la[0]=a,this.la[1]=b,this.la[2]=0,this.ka[0]=Math.cos(c),this.ka[1]=Math.sin(c),this.ka[2]=0,this.B.setPosition(...this.la),
this.B.setOrientation(...this.ka))}Ue(a){this.ha=a}qc(){}Qe(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Nb,tag:this.$,duration:this.ga(),volume:this.tb,isPlaying:this.IsPlaying(),playbackTime:this.Da(),playbackRate:this.sa,uid:this.ha,bufferOriginalUrl:this.oc(),bufferUrl:"",bufferType:this.nc(),isMusic:this.va(),isLooping:this.W,isMuted:this.Ha,resumePosition:this.qc(),pan:this.He()}}Ec(a){this.wd(a.playbackRate);this.ud(a.isMuted)}He(){if(!this.B)return null;const a=
this.B;return{pos:this.la,orient:this.ka,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ha}}Oe(a){if(a){this.Db(!0);a=this.B;var b=a.pos;this.la[0]=b[0];this.la[1]=b[1];this.la[2]=b[2];b=a.orient;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];a.setPosition(...this.la);a.setOrientation(...this.ka);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ha=a.uid}else this.Db(!1)}}}"use strict";
self.xe=class extends self.kd{constructor(e,a,b){super(e,a,b);this.L.pb.connect(this.M);this.L.onended=()=>this.Fc()}c(){this.oa();this.L.pb.disconnect();super.c()}O(){return this.L.O()}Fc(){this.H=!0;this.ha=-1;this.i.tc("ended",this.$,this.Nb)}T(){return this.O().ended}kc(){return this.H?!0:this.T()}Da(){let e=this.O().currentTime;this.W||(e=Math.min(e,this.ga()));return e}Play(e,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.Fb(a);c.muted&&(c.muted=!1);
if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,g)}this.i.Z(c);this.G=this.H=!1;this.W=e;this.sa=1}oa(){const e=this.O();e.paused||e.pause();this.i.aa(e);this.H=!0;this.G=!1;this.ha=-1}Ua(){if(!(this.G||this.H||this.T())){var e=this.O();e.paused||e.pause();this.i.aa(e);this.G=!0}}Cb(){!this.G||this.H||this.T()||(this.i.Z(this.O()),this.G=!1)}Lb(){this.O().muted=this.Ha||this.Bb()}vc(e){e=!!e;this.W!==e&&(this.W=
e,this.O().loop=e)}Fa(){let e=this.sa;this.Wc&&(e*=this.i.hc);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}uc(e){if(!this.H&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}qc(){return this.Da()}wc(e){e?this.IsPlaying()?(this.O().pause(),this.ma=!0):this.ma=!1:this.ma&&(this.i.Z(this.O()),this.ma=!1)}};"use strict";function X(e){e.j&&e.j.disconnect();e.j=null;e.Za=null}
self.ze=class extends self.kd{constructor(e,a,b){super(e,a,b);this.j=null;this.Zb=c=>this.Fc(c);this.Sc=!0;this.Za=null;this.N=this.$b=this.ac=0;this.$c=1}c(){this.oa();X(this);this.Zb=null;super.c()}Fc(e){this.G||this.ma||e.target!==this.Za||(this.H=this.Sc=!0,this.ha=-1,X(this),this.i.tc("ended",this.$,this.Nb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Sc}kc(){return!this.j||this.H?!0:this.T()}Da(){let e;e=this.G?this.N:this.$b+(this.zb()-this.ac)*this.sa;this.W||(e=Math.min(e,this.ga()));
return e}Play(e,a,b,c){this.$c=1;this.Fb(a);X(this);this.j=this.X().createBufferSource();this.j.buffer=this.L.ba;this.j.connect(this.M);this.Za=this.j;this.j.onended=this.Zb;this.j.loop=e;this.j.start(c,b);this.G=this.H=this.Sc=!1;this.W=e;this.sa=1;this.ac=this.zb();this.$b=b}oa(){if(this.j)try{this.j.stop(0)}catch(e){}this.H=!0;this.G=!1;this.ha=-1}Ua(){this.G||this.H||this.T()||(this.N=this.Da(),this.W&&(this.N%=this.ga()),this.G=!0,this.j.stop(0))}Cb(){!this.G||this.H||this.T()||(X(this),this.j=
this.X().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Zb,this.j.loop=this.W,this.Mb(),this.Fa(),this.j.start(0,this.N),this.ac=this.zb(),this.$b=this.N,this.G=!1)}pc(){return super.pc()*this.$c}Lb(){this.$c=this.Ha||this.Bb()?0:1;this.Mb()}vc(e){e=!!e;this.W!==e&&(this.W=e,this.j&&(this.j.loop=e))}Fa(){let e=this.sa;this.Wc&&(e*=this.i.hc);this.j&&(this.j.playbackRate.value=e)}uc(e){this.H||this.T()||(this.G?this.N=e:(this.Ua(),this.N=e,this.Cb()))}qc(){return this.N}wc(e){e?
this.IsPlaying()?(this.ma=!0,this.N=this.Da(),this.W&&(this.N%=this.ga()),this.j.stop(0)):this.ma=!1:this.ma&&(X(this),this.j=this.X().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Zb,this.j.loop=this.W,this.Mb(),this.Fa(),this.j.start(0,this.N),this.ac=this.zb(),this.$b=this.N,this.ma=!1)}Ec(e){super.Ec(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.X();this.Vd=-1;this.R=this.$="";this.g=null}c(){this.f=null}rg(a){this.Vd=a}zg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ra(){return{type:this.R,tag:this.$,params:this.g}}}
self.qe=class extends e{constructor(a,b,c,g,m,p,u){super(a);this.R="filter";this.g=[b,c,g,m,p,u];this.l=this.o();this.b=this.o();this.b.gain.value=u;this.a=this.o();this.a.gain.value=1-u;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.oe=class extends e{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.mb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=c;this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b);this.mb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.mb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.mb.disconnect();this.U.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){const m=self.fa.nd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.cb.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.ne=class extends e{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Qd=this.Pd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.bb=this.f.createConvolver();this.bb.normalize=c;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}c(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}ng(a,b){this.Pd=a;this.Qd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Pd;a.bufferUrl="";a.bufferType=this.Qd;return a}};self.re=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.fb=this.o();this.fb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,c,g)}}};self.te=class extends e{constructor(a,b,c,g,m,p,u){super(a);this.R="phaser";this.g=[b,c,g,m,p,u];this.l=this.o();this.a=this.o();this.a.gain.value=1-u/2;this.b=this.o();this.b.gain.value=u/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.se=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,c,g){const m=self.fa.nd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.ve=class extends e{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.I.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.ue=class extends e{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.sb=this.o();this.sb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.sb.gain);this.s.start(0);this.l.connect(this.sb);this.l.connect(this.a);this.sb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.sb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.pe=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.cc=this.o();this.bc=this.o();this.og(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ic=this.f.createWaveShaper();this.Oc=new Float32Array(65536);this.mf(b,c);this.ic.curve=this.Oc;this.l.connect(this.cc);this.l.connect(this.a);this.cc.connect(this.ic);this.ic.connect(this.bc);
this.bc.connect(this.b)}c(){this.l.disconnect();this.cc.disconnect();this.ic.disconnect();this.bc.disconnect();this.b.disconnect();this.a.disconnect();super.c()}og(a,b){.01>a&&(a=.01);this.cc.gain.value=a;this.bc.gain.value=Math.pow(1/a,.6)*b}mf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.Bg(g,a,b);this.Oc[32768+c]=g;this.Oc[32768-c-1]=-g}}Bg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.fa.Tg(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}Y(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.me=class extends e{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}};
self.le=class extends e{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Td=new Float32Array(this.h.frequencyBinCount);this.ee=new Uint8Array(b);this.ce=this.Ka=0;this.i.We(this)}c(){this.i.gg(this);this.h.disconnect();super.c()}wa(){this.h.getFloatFrequencyData(this.Td);this.h.getByteTimeDomainData(this.ee);const a=this.h.fftSize;let b=this.Ka=0;for(var c=0;c<a;++c){let g=(this.ee[c]-128)/128;0>g&&(g=-g);
this.Ka<g&&(this.Ka=g);b+=g*g}c=self.fa.Me;this.Ka=c(this.Ka);this.ce=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}Y(){}Ge(){return{tag:this.$,index:this.Vd,peak:this.Ka,rms:this.ce,binCount:this.h.frequencyBinCount,freqBins:this.Td}}}}"use strict";self.Va.wb(class extends self.yb{constructor(e){super(e,"mouse");G(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
self.Va.wb(class extends self.Be{constructor(e){super(e,"video");this.fc=this.Tb=this.$a=!1;this.Yb=this.Qg=0;this.Pc=new WeakSet;G(this,"init",a=>this.Gf(a));Q(this,"play",a=>this.Nf(a));Q(this,"pause",a=>this.Mf(a));Q(this,"set-source",(a,b)=>this.Xf(a,b));Q(this,"set-playback-time",(a,b)=>this.Wf(a,b));Q(this,"set-looping",(a,b)=>this.Uf(a,b));Q(this,"set-muted",(a,b)=>this.Vf(a,b));Q(this,"set-volume",(a,b)=>this.Zf(a,b));self.C3Video_GetElement=a=>this.V.get(a)}async Gf(e){this.Tb=e.isInWorker;
e=document.createElement("video");this.fc=!!e.requestVideoFrameCallback;return{"video/webm":!!e.canPlayType("video/webm"),"video/ogg":!!e.canPlayType("video/ogg"),"video/mp4":!!e.canPlayType("video/mp4")}}Z(e){this.v.Z(e);this.Tb&&this.fc&&-1===e.c3_rvfcId&&(e.c3_rvfcId=e.requestVideoFrameCallback(()=>this.Id(e)))}aa(e){this.v.aa(e);this.Tb&&this.fc&&-1!==e.c3_rvfcId&&(e.cancelVideoFrameCallback(e.c3_rvfcId),e.c3_rvfcId=-1)}async Id(e){if(!this.Pc.has(e)){e.c3_rvfcId=e.requestVideoFrameCallback(()=>
this.Id(e));try{const a=e.c3_sequenceNumber++,b=await createImageBitmap(e);a>e.c3_lastFrameSequence&&(e.c3_imageBitmap=b,e.c3_lastFrameSequence=a)}catch(a){}}}md(e,a){const b=document.createElement("video");b.crossOrigin="anonymous";b.playsInline=!0;b.c3_imageBitmap=null;b.c3_rvfcId=-1;b.c3_sequenceNumber=0;b.c3_lastFrameSequence=-1;b.addEventListener("canplay",()=>this.pa(b,e,0));b.addEventListener("canplaythrough",()=>this.pa(b,e,1));b.addEventListener("ended",()=>this.pa(b,e,2));b.addEventListener("error",
()=>this.pa(b,e,3));b.addEventListener("loadstart",()=>this.pa(b,e,4));b.addEventListener("playing",()=>this.pa(b,e,5));b.addEventListener("pause",()=>this.pa(b,e,6));b.addEventListener("stalled",()=>this.pa(b,e,7));const c=a.autoplay;0===c?(b.autoplay=!1,b.preload="none"):1===c?(b.autoplay=!1,b.preload="auto"):b.autoplay=!0;a.src&&(b.src=a.src);2===c&&this.Z(b);this.Yb++;J(this);return b}pa(e,a,b){this.Pc.has(e)||P(this,"playback-event",a,{type:b})}xd(){}od(e){this.aa(e);e&&!e.paused&&!e.ended&&
0<e.currentTime&&e.pause();e.src="";this.Yb=Math.max(this.Yb-1,0);0===this.Yb&&K(this);this.Pc.add(e)}Nf(e){this.Z(e)}Mf(e){this.aa(e);e.pause()}Xf(e,a){e.src=a.src;e.load()}Wf(e,a){try{e.currentTime=a.time}catch(b){console.error("[Video] Exception setting playback time: ",b)}}Uf(e,a){e.loop=a.isLooping}Vf(e,a){e.muted=a.isMuted}Zf(e,a){e.volume=a.volume}wa(){const e={},a={sequenceNumber:this.Qg++,videoData:e},b=[],c=[];for(const [g,m]of this.V.entries()){const p={currentTime:m.currentTime,duration:m.duration,
videoWidth:m.videoWidth,videoHeight:m.videoHeight};if(this.Tb)if(this.fc){const u=m.c3_imageBitmap;m.c3_imageBitmap=null;(p.imageBitmap=u)&&b.push(u)}else c.push(createImageBitmap(m).then(u=>{p.imageBitmap=u;b.push(u)}).catch(()=>{p.imageBitmap=null}));e[g.toString()]=p}Promise.all(c).then(()=>y(this,"state",a,!1,b))}});
